### PR TITLE
keycloak_quarkus: use absolute path for certificate files

### PR DESCRIPTION
**Pull request by cattz**
If you want to use a certificate for both Keycloak and Nginx, the cert files are quite unlikely to be under `keycloak.home`
Even in case you want to keep the under Keycloak path, you can always define the variable:

```
   keycloak_quarkus_cert_file: "{{ keycloak.home }}/conf/my_keycloak_cert.pem"
   keycloak_quarkus_key_file: "{{ keycloak.home }}/conf/my_keycloak_key.pem"
```
This change will break your previous configuration (unless you use the default values).
To fix your config for the new changes, you will have use full paths for the 2 variables mentioned above. For example:
```
   keycloak_quarkus_key_file: "/etc/ssl/certs/my_keycloak_key.pem"
   keycloak_quarkus_cert_file: "/etc/ssl/certs/my_keycloak_cert.pem"
```

### CODE REVIEW

**Comment by guidograzioli** [comment]
I am ok with the change, but you'll need to update meta/argument_specs, defaults/main.yml and README as well

**Comment by cattz** [comment]
This change will break existing configurations, unless they are using the default value. Not sure how to warn users about this

**Comment by cattz** [comment]
I'm not sure on why CI is failing now

**Comment by guidograzioli** [comment]
Found the issue here: 
https://github.com/ansible-middleware/keycloak/blob/main/molecule/quarkus/converge.yml#L12
(the molecule test playbook was not using default and broke). 
The certs are created in the prepare step here:
https://github.com/ansible-middleware/keycloak/blob/main/molecule/quarkus/prepare.yml#L9
Please amend the test config so it passes

**Comment by guidograzioli** [comment]
LGTM (again) thanks for contributing

**Pull request merged**
