### PR TITLE
feat: add a destination variable for the log link

### LINKED ISSUE #79: Add a destination variable for the log link
##### SUMMARY

It is not possible to modify the destination of the log link.

By default the keycloak logs are physically in /opt, I would like them to be in /var/log.

https://github.com/ansible-middleware/keycloak/blob/01fd2cc4fdb1037577b9a6e48b3120fbc9c542d7/roles/keycloak_quarkus/tasks/main.yml#L63-L69

Task : [roles/keycloak_quarkus/tasks/main.yml](https://github.com/ansible-middleware/keycloak/blob/01fd2cc4fdb1037577b9a6e48b3120fbc9c542d7/roles/keycloak_quarkus/tasks/main.yml#L67) 

##### ISSUE TYPE
 - Feature Idea

### PR DESCRIPTION
**Pull request by jacobdotcosta**
Closes #79

### CODE REVIEW

**Comment by guidograzioli** [comment]
Thank you very much for your contribution! Very clean PR; do you mind adding the parameter line in the roles README tables?

**Comment by guidograzioli** [comment]
Sorry, I meant here:
https://github.com/ansible-middleware/keycloak/blob/main/roles/keycloak_quarkus/README.md?plain=1#L96
and similar for keycloak README

**Comment by jacobdotcosta** [comment]
Added the parameters to both the roles README files.

Also renamed the new parameter on the `keycloak` role as it had the wrong prefix. I named it `keycloak_quarkus_log_target`, as a copy of the `keycloak_quarkus` parameter, when it should be just `keycloak_log_target`.

**Review by guidograzioli — APPROVED** [review]
lgtm

**Pull request merged**
